#!/bin/ksh
#
# $Id $
#
# by Helmut K. C. Tessarek
# name: create_runstats
# parameter[s]: -d <database name> [-m <method>] [-t <tablespace>] [-h]
#       method: 1 || with distribution and detailed indexes all (default)
#               2 || 
#               3 || 

#
#  global variables
#

PROGNAME=$(/bin/basename $0)

#
# parse command line into arguments
#

set -- `getopt d:m:t:h $*`
# check result of parsing
if [ $? != 0 ]
then
        exit 1
fi
while [ $1 != -- ]
do
        case $1 in
        -d)     # set up the -d flag
                DFLG=1
                DARG=$2
                shift;;
        -m)     # set up the -m flag
                MFLG=1
                MARG=$2
                shift;;
	-t)     # set up the -t flag
                TFLG=1
                TARG=$2
                shift;;
	-h)     # set up the -h flag
                HFLG=1;;
        esac
        shift   # next flag
done
shift   # skip --

#
#  functions
#

function ERR
{
  echo "$PROGNAME: ERROR: $*"
  exit 1
}

function HELP
{
  echo "Usage: $PROGNAME -d <database name> [-m <method>] [-t <tablespace>] [-h]"
  echo "       <method> 1 - with distribution and detailed indexes all (default)"
  exit 1
}

if [ "$HFLG" = "1" ]
then
  HELP
fi

if [ "$DFLG" != "1" ]
then
  HELP
fi

if [ "$MFLG" != "1" ]
then
  MARG=1
fi

if [ "$MARG" != "1" -a "$MARG" != "2" -a "$MARG" != "3" ]
then
  HELP
fi

if [ "$MARG" = "1" ]
then
  FNP=tables
  STMTSTART="runstats on table"
  STMTEND="with distribution and detailed indexes all"
fi

#
#  main
#

if [ -z "$DB2INSTANCE"  ]; then
  ERR "DB2 environment not set"
fi

db2 connect to $DARG >/dev/null

if [ "$?" != "0" ]; then
  echo Cannot connect to $DARG
  echo Error.
  exit 1
fi

echo Connected to database: $DARG

if [ "$TFLG" = "1" ]
then
  db2 "select tbspace from syscat.tablespaces where tbspace = '${TARG}'" >/dev/null
  if [ "$?" != "0" ]; then
    echo Tablespace $TARG does not exist!!!
    echo Info: tablespace parameter is case-sensitive.
    echo Available Tablespaces:
    echo ----------------------
    db2 -x "select tbspace from syscat.tablespaces"
    echo ----------------------
    echo Error.
    db2 connect reset >/dev/null
    db2 terminate >/dev/null
    exit 1
  fi
  STMT="select '${STMTSTART} \"' || rtrim(tabschema) || '\".\"' || rtrim(tabname) || '\" ${STMTEND};' from syscat.tables where tbspace = '${TARG}'"
else
  STMT="select '${STMTSTART} \"' || rtrim(tabschema) || '\".\"' || rtrim(tabname) || '\" ${STMTEND};' from syscat.tables where tbspace not like 'SYS%'"
  TARG=ALL
fi

FN=runstats_${FNP}_${TARG}.sql

echo Creating DB2 script: $FN
db2 -x "${STMT}" >$FN

db2 connect reset >/dev/null
db2 terminate >/dev/null

echo Success.

exit 0
### EOF ###
