#!/bin/ksh
#
# $Id$
#
# by Helmut K. C. Tessarek
# name: db2clean
# parameter[s]: none

#
#  global variables
#

PROGNAME=$(/bin/basename $0)
SU=/bin/su

if [ "`uname`" = "Linux" ]
then
	_DB2_INST_DIR=/opt/ibm/db2/V9.1
else
	_DB2_INST_DIR=/opt/IBM/db2/V9.1
fi
_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist
_DB2_DASLIST=$_DB2_INST_DIR/instance/daslist
_DB2_FM=$_DB2_INST_DIR/bin/db2fm
_DB2_FMCU=$_DB2_INST_DIR/bin/db2fmcu

#
#  functions
#

function ERR
{
  echo "$PROGNAME: ERROR: $*"
  exit 1
}

#
#  main
#

if [ "`id -u`" != "0" ]; then
  ERR "you must be root to run this program"
fi

if [ ! -d $_DB2_INST_DIR ]; then
  ERR "Directory $_DB2_INST_DIR not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_INSTLIST ]; then
  ERR "File $_DB2_INSTLIST not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_DASLIST ]; then
  ERR "File $_DB2_DASLIST not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_FM ]; then
  ERR "File $_DB2_FM not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_FMCU ]; then
  ERR "File $_DB2_FMCU not found (db2 may not be installed)"
fi

for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  echo
  echo Shutting down instance - $ACT_INST
  echo
  $SU - $ACT_INST -c "db2 force applications all; db2 terminate; db2stop; db2licd -end"
done

ACT_DAS=$($_DB2_DASLIST)
echo
echo Shutting down admin server - $ACT_DAS
echo
$SU - $ACT_DAS -c "db2admin stop"

if [ "`uname`" = "AIX" ]
then
	echo
	echo unload unused shared libraries
	echo
	/usr/sbin/slibclean
fi

echo
echo disable the Fault Monitor Coordinator
echo
$_DB2_FMCU -d

for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  echo
  echo stop the Fault Monitor Daemon for instance  - $ACT_INST
  echo
  $_DB2_FM -D -i $ACT_INST 
done

for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  echo
  echo clean all DB2 interprocess communications for instance  - $ACT_INST
  echo
  $SU - $ACT_INST -c "ipclean" 
done

exit 0
### EOF ###
