#!/bin/ksh
#
# by Helmut K. C. Tessarek
# name: db2clean
# parameter[s]: [-b <baseInstallpathOfDB2>] [-h]

#
#  global variables
#

# put path of most recent version first
DFTPATH="/opt/ibm/db2/V9.7 /opt/IBM/db2/V9.7 /opt/ibm/db2/V9.5 /opt/IBM/db2/V9.5 /opt/ibm/db2/V9.1 /opt/IBM/db2/V9.1 /opt/IBM/db2/V8.1 /usr/opt/db2_08_01"
PROGNAME=$(/bin/basename $0)
SU=/bin/su

#
# parse command line into arguments
#

set -- `getopt b:h $*`
# check result of parsing
if [ $? != 0 ]
then
        exit 1
fi
while [ $1 != -- ]
do
        case $1 in
        -b)     # set up the -b flag
                BFLG=1
                BARG=$2
                shift;;
        -h)     # set up the -h flag
                HFLG=1;;
        esac
        shift   # next flag
done
shift   # skip --

#
#  functions
#

function ERR
{
  echo "$PROGNAME: ERROR: $*"
  exit 1
}

function HELP
{
  echo "Usage: $PROGNAME [-b <baseInstallpathOfDB2>] [-h]"
  exit 1
}

if [ "$HFLG" = "1" ]
then
  HELP
fi

#
#  main
#

for p in $DFTPATH
do
  if [ -d $p ]
  then
    _DB2_INST_DIR=$p
    break
  fi
done

if [ ! -z "$BARG" ]
then
  _DB2_INST_DIR=$BARG
fi

if [ -z "$_DB2_INST_DIR" ]
then
  ERR "install directory not found. specify it with -b option"
fi

_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist
_DB2_DASLIST=$_DB2_INST_DIR/instance/daslist
_DB2_FM=$_DB2_INST_DIR/bin/db2fm
_DB2_FMCU=$_DB2_INST_DIR/bin/db2fmcu

if [ "`id -u`" != "0" ]; then
  ERR "you must be root to run this program"
fi

if [ ! -d $_DB2_INST_DIR ]; then
  ERR "Directory $_DB2_INST_DIR not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_INSTLIST ]; then
  ERR "File $_DB2_INSTLIST not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_DASLIST ]; then
  ERR "File $_DB2_DASLIST not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_FM ]; then
  ERR "File $_DB2_FM not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_FMCU ]; then
  ERR "File $_DB2_FMCU not found (db2 may not be installed)"
fi

for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  echo
  echo Shutting down instance - $ACT_INST
  echo
  $SU - $ACT_INST -c "db2 force applications all; db2 terminate; db2stop; db2licd -end"
done

ACT_DAS=$($_DB2_DASLIST)
echo
echo Shutting down admin server - $ACT_DAS
echo
$SU - $ACT_DAS -c "db2admin stop"

if [ "`uname`" = "AIX" ]
then
	echo
	echo unload unused shared libraries
	echo
	/usr/sbin/slibclean
fi

echo
echo disable the Fault Monitor Coordinator
echo
$_DB2_FMCU -d

for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  echo
  echo stop the Fault Monitor Daemon for instance  - $ACT_INST
  echo
  $_DB2_FM -D -i $ACT_INST 
done

for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  echo
  echo clean all DB2 interprocess communications for instance  - $ACT_INST
  echo
  $SU - $ACT_INST -c "ipclean" 
done

exit 0
### EOF ###
