#!/bin/ksh
#
# $Id$
#
# by Helmut K. C. Tessarek
# name: db2dbs
# parameter[s]: [-f <scriptname>] [-b <baseInstallpathOfDB2>] [-h]

#
#  global variables
#

# put path of most recent version first
DFTPATH="/opt/ibm/db2/V9.5 /opt/IBM/db2/V9.5 /opt/ibm/db2/V9.1 /opt/IBM/db2/V9.1 /opt/IBM/db2/V8.1 /usr/opt/db2_08_01"
PROGNAME=$(/bin/basename $0)
SU=/bin/su

#
# parse command line into arguments
#

set -- `getopt b:f:h $*`
# check result of parsing
if [ $? != 0 ]
then
        exit 1
fi
while [ $1 != -- ]
do
        case $1 in
        -b)     # set up the -b flag
                BFLG=1
                BARG=$2
                shift;;
        -f)     # set up the -f flag
                FFLG=1
                FARG=$2
                shift;;
        -h)     # set up the -h flag
                HFLG=1;;
        esac
        shift   # next flag
done
shift   # skip --

#
#  functions
#

function ERR
{
  echo "$PROGNAME: ERROR: $*"
  exit 1
}

function HELP
{
  echo "Usage: $PROGNAME [-f <scriptname>] [-b <baseInstallpathOfDB2>] [-h]"
  exit 1
}

if [ "$HFLG" = "1" ]
then
  HELP
fi

#
#  main
#

for p in $DFTPATH
do
  if [ -d $p ]
  then
    _DB2_INST_DIR=$p
    break
  fi
done

if [ ! -z "$BARG" ]
then
  _DB2_INST_DIR=$BARG
fi

if [ -z "$_DB2_INST_DIR" ]
then
  ERR "install directory not found. specify it with -b option"
fi

_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist

if [ "`id -u`" != "0" ]; then
  ERR "you must be root to run this program"
fi

if [ ! -d $_DB2_INST_DIR ]; then
  ERR "Directory $_DB2_INST_DIR not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_INSTLIST ]; then
  ERR "File $_DB2_INSTLIST not found (db2 may not be installed)"
fi

for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  echo
  echo Instance - $ACT_INST
  echo

  for ACT_DB in $($SU - $ACT_INST -c "db2 list db directory | awk '\$2 == \"alias\"  { alias = \$4;printf \"%s\\n\", alias}'")
  do
     if [ "`grep --version 2>/dev/null|grep -c GNU`" = "1" ]
     then
       LOCAL=$($SU - $ACT_INST -c "db2 list db directory show detail | grep -E \"alias.*$ACT_DB\" -A 5 | tail -1 | awk '{print \$5}'")
     else
       LOCAL=$($SU - $ACT_INST -c "db2 list db directory show detail | grep -p -E \"alias.*$ACT_DB\" | awk ' \$1 == \"Directory\"  { entry = \$5; printf \"%s\", entry; next }'")
     fi
     if [ "$LOCAL" == "Indirect" ]; then
       echo Database $ACT_DB

       if [ ! -z "$FARG" ]; then
          sed "s/DBNAME/$ACT_DB/g" $FARG >/tmp/$ACT_DB
          
          $SU - $ACT_INST -c "db2 -tvf /tmp/$ACT_DB"
          
          rm -f /tmp/$ACT_DB
       fi
       
     fi
  done
done

echo
exit 0
### EOF ###

