#!/bin/ksh
#
# $Id$
#
# by Helmut K. C. Tessarek
# name: db2updt
# parameter[s]: [-b <baseInstallpathOfDB2>] [-i] [-a] [-h]

#
#  global variables
#

# put path of most recent version first
DFTPATH="/opt/ibm/db2/V9.7 /opt/IBM/db2/V9.7 /opt/ibm/db2/V9.5 /opt/IBM/db2/V9.5 /opt/ibm/db2/V9.1 /opt/IBM/db2/V9.1 /opt/IBM/db2/V8.1 /usr/opt/db2_08_01"
PROGNAME=$(/bin/basename $0)
SU=/bin/su

#
# parse command line into arguments
#

set -- `getopt b:h $*`
# check result of parsing
if [ $? != 0 ]
then
        exit 1
fi
while [ $1 != -- ]
do
        case $1 in
        -b)     # set up the -b flag
                BFLG=1
                BARG=$2
                shift;;
        -h)     # set up the -h flag
                HFLG=1;;
        -a)     # set up the -a flag
                AFLG=1;;
        -i)     # set up the -i flag
                IFLG=1;;
        esac
        shift   # next flag
done
shift   # skip --

#
#  functions
#

function ERR
{
  echo "$PROGNAME: ERROR: $*"
  exit 1
}

function HELP
{
  echo "Usage: $PROGNAME [-b <baseInstallpathOfDB2>] [-i] [-a] [-h]"
  exit 1
}

if [ "$HFLG" = "1" ]
then
  HELP
fi

#
#  main
#

for p in $DFTPATH
do
  if [ -d $p ]
  then
    _DB2_INST_DIR=$p
    break
  fi
done

if [ ! -z "$BARG" ]
then
  _DB2_INST_DIR=$BARG
fi

if [ -z "$_DB2_INST_DIR" ]
then
  ERR "install directory not found. specify it with -b option"
fi

_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist
_DB2_DASLIST=$_DB2_INST_DIR/instance/daslist
_DB2_IUPDT=$_DB2_INST_DIR/instance/db2iupdt
_DB2_DASUPDT=$_DB2_INST_DIR/instance/dasupdt

for i in 8 9 10 11
do
  if [ -x $_DB2_INST_DIR/bin/db2updv$i ]
  then
    _DB2_UPD=db2updv$i
  fi
done

if [ "`id -u`" != "0" ]; then
  ERR "you must be root to run this program"
fi

if [ ! -d $_DB2_INST_DIR ]; then
  ERR "Directory $_DB2_INST_DIR not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_INSTLIST ]; then
  ERR "File $_DB2_INSTLIST not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_DASLIST ]; then
  ERR "File $_DB2_DASLIST not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_IUPDT ]; then
  ERR "File $_DB2_IUPDT not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_DASUPDT ]; then
  ERR "File $_DB2_DASUPDT not found (db2 may not be installed)"
fi

for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  if [ "$IFLG" = "1" ]
  then
    echo
    echo Updating instance - $ACT_INST
    echo
    $_DB2_IUPDT $ACT_INST
  fi
  $SU - $ACT_INST -c "db2start"
  
  for ACT_DB in $($SU - $ACT_INST -c "db2 list db directory | awk '\$2 == \"alias\"  { alias = \$4;printf \"%s\\n\", alias}'")
  do
     ## db2start
     if [ "`grep --version 2>/dev/null|grep -c GNU`" = "1" ]
     then
       LOCAL=$($SU - $ACT_INST -c "db2 list db directory show detail | grep -E \"alias.*$ACT_DB\" -A 5 | tail -1 | awk '{print \$5}'")
     else
       LOCAL=$($SU - $ACT_INST -c "db2 list db directory show detail | grep -p -E \"alias.*$ACT_DB\" | awk ' \$1 == \"Directory\"  { entry = \$5; printf \"%s\", entry; next }'")
     fi
     if [ "$LOCAL" == "Indirect" ]; then
       echo
       echo Updating database $ACT_DB
       echo
       ## bind and update
       
       $SU - $ACT_INST -c "db2 CONNECT TO $ACT_DB;\
                           db2 BIND ~/sqllib/bnd/@db2ubind.lst GRANT PUBLIC BLOCKING ALL;\
                           db2 BIND ~/sqllib/bnd/@db2cli.lst GRANT PUBLIC BLOCKING ALL;\
                           db2 BIND ~/sqllib/bnd/db2schema.bnd BLOCKING ALL GRANT PUBLIC sqlerror continue;\
                           db2 CONNECT RESET"
       
       if [ ! -z "$_DB2_UPD" ]
       then
         $SU - $ACT_INST -c "$_DB2_UPD -d $ACT_DB"
       fi
     fi
  done
done

if [ "$AFLG" = "1" ]
then
  ACT_DAS=$($_DB2_DASLIST)

  if [ ! -z "$ACT_DAS" ]
  then
    echo
    echo Updating admin server - $ACT_DAS
    echo

    ## dasupdt

    $_DB2_DASUPDT $ACT_DAS

    $SU - $ACT_DAS -c "db2admin stop"
  else
    echo
    echo No admin server installed
    echo
  fi
fi

exit 0
### EOF ###
