#!/bin/ksh
#
# by Helmut K. C. Tessarek, version 0.4
# name: db2updt
# parameter[s]: none

#
#  global variables
#

PROGNAME=$(/bin/basename $0)
SU=/bin/su

if [ "`uname`" = "Linux" ]
then
	_DB2_INST_DIR=/opt/IBM/db2/V8.1
else
	_DB2_INST_DIR=/usr/opt/db2_08_01
fi
_DB2_INSTLIST=$_DB2_INST_DIR/instance/db2ilist
_DB2_DASLIST=$_DB2_INST_DIR/instance/daslist
_DB2_IUPDT=$_DB2_INST_DIR/instance/db2iupdt
_DB2_DASUPDT=$_DB2_INST_DIR/instance/dasupdt

#
#  functions
#

function ERR
{
  echo "$PROGNAME: ERROR: $*"
  exit 1
}

#
#  main
#

if [ "`id -u`" != "0" ]; then
  ERR "you must be root to run this program"
fi

if [ ! -d $_DB2_INST_DIR ]; then
  ERR "Directory $_DB2_INST_DIR not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_INSTLIST ]; then
  ERR "File $_DB2_INSTLIST not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_DASLIST ]; then
  ERR "File $_DB2_DASLIST not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_IUPDT ]; then
  ERR "File $_DB2_IUPDT not found (db2 may not be installed)"
fi
if [ ! -x $_DB2_DASUPDT ]; then
  ERR "File $_DB2_DASUPDT not found (db2 may not be installed)"
fi


for ACT_INST in $($_DB2_INSTLIST 2>/dev/null)
do
  echo
  echo Updating instance - $ACT_INST
  echo
  
  ## db2iupdt
  
  $_DB2_IUPDT $ACT_INST
  
  $SU - $ACT_INST -c "db2start"
  
  for ACT_DB in $($SU - $ACT_INST -c "db2 list db directory | awk '\$2 == \"alias\"  { alias = \$4;printf \"%s\\n\", alias}'")
  do
     ## db2start
     if [ "`grep --version 2>/dev/null|grep -c GNU`" = "1" ]
     then
       LOCAL=$($SU - $ACT_INST -c "db2 list db directory show detail | grep -E \"alias.*$ACT_DB\" -A 5 | tail -1 | awk '{print \$5}'")
     else
       LOCAL=$($SU - $ACT_INST -c "db2 list db directory show detail | grep -p -E \"alias.*$ACT_DB\" | awk ' \$1 == \"Directory\"  { entry = \$5; printf \"%s\", entry; next }'")
     fi
     if [ "$LOCAL" == "Indirect" ]; then
       echo
       echo Updating database $ACT_DB
       echo
       ## bind and update
       
       $SU - $ACT_INST -c "db2 CONNECT TO $ACT_DB;\
                           db2 BIND ~/sqllib/bnd/@db2ubind.lst GRANT PUBLIC BLOCKING ALL;\
                           db2 BIND ~/sqllib/bnd/@db2cli.lst GRANT PUBLIC BLOCKING ALL;\
                           db2 BIND ~/sqllib/bnd/db2schema.bnd BLOCKING ALL GRANT PUBLIC sqlerror continue;\
                           db2 CONNECT RESET;\
                           db2updv8 -d $ACT_DB"
     fi
  done
done

ACT_DAS=$($_DB2_DASLIST)

if [ ! -z "$ACT_DAS" ]
then
  echo
  echo Updating admin server - $ACT_DAS
  echo

  ## dasupdt

  $_DB2_DASUPDT $ACT_DAS

  $SU - $ACT_DAS -c "db2admin start"
else
  echo
  echo No admin server installed
  echo
fi

exit 0
### EOF ###
